name: CI/CD action

on:
  push:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-lates
    steps:
      - name: Проверить изменения
        uses: actions/checkout@v2

      - name: Установка python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Установка зависимостей
        run: pip install -r requirements.txt

      - name: Линтер
        run: flake8 demo1 --exclude migrations ignore E501,F401,E302,W293,W391,W292

